# 配置文件请严格遵循 yaml 语法格式，yaml 学习地址:
#  https://ansible-tran.readthedocs.io/en/latest/docs/YAMLSyntax.html
#  http://einverne.github.io/post/2015/08/yaml.html

# 切换微信号
is_forced_switch: False

# 是否开启自动回复,False
is_auto_relay: True

#图灵机器人(http://www.tuling123.com/)免费用户每天可用 100 条。
#请在官网注册并申请 apikey ,userID。
turing_conf:
  # 是否开启自动回复,只可选 False && True
  apiKey: ''
  userId: ''

# 指定自动回复的好友名单。
# - '好友1'
# - '好友2'
auto_reply_names:
  - '新希望-兰太敏'
  - '新希望-蒋禄磊'

#------------------------ 定时时间功能--------------------------
alarm_info:
  #True 开启定时提醒，False 关闭
  is_alarm: True
  #定时发送时间
  alarm_timed: '9:30'

girlfriend_infos:
  - #女友微信昵称或者备注名，不能输入微信号。
    wechat_name: '新希望-兰太敏'
    #女友所在城市，用于发送天气。（可空）
    city_name: '上海'
    # 格言渠道（1 : ONE●一个， 2 : 词霸（每日英语，双语）  4 : 一言)(可空)
    dictum_channel : 2
    # 从那天开始勾搭的(最终效果为：宝贝这是我们在一起的第 111 天)（可空）
    start_date: '2019-07-17'
    # 后缀（可空）
    sweet_words: '来自究极开发蒋禄磊的小迷弟。'


#  如果你有多个好友需要发送，则参照这个样式，复制即可
#  如不需要，则删除或注解下面所有的数据
  - wechat_name: '新希望-蒋禄磊'
    city_name: '上海'
    dictum_channel : 4
    start_date: '2019-07-17'
    sweet_words: '来自交易一哥兰太敏的卧底。'


